## 3. 도형 그리기

### 빈 스케치북 만들기

In [1]:
import cv2
import numpy as np 

# 세로 480 x 가로 640, 3channel에 해당되는 스케치북 만들기 
sketchbook = np.zeros((480, 640, 3), dtype = np.uint8)
'''sketchbook[:] = (255, 255, 255) # 전체 공간을 흰 색으로 채우기 (BGR)
print (sketchbook)'''

cv2.imshow('sketchbook', sketchbook)
cv2.waitKey(0)
cv2.destroyAllWindows()

# mac에서 opencv 팝업창 안닫힐때 뒤에 항상 붙여주기
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


2023-11-12 21:36:53.299 Python[81671:900454] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.


-1

### 일부 영역 색칠

In [4]:
import cv2
import numpy as np 

sketchbook = np.zeros((480, 640, 3), dtype = np.uint8)
sketchbook[100:200, 200:300] = (255, 255, 255) 
# 세로 기준으로 100에서 200까지, 가로 기준으로 200에서 300까지 흰색으로 칠함

cv2.imshow('sketchbook', sketchbook)
cv2.waitKey(0)
cv2.destroyAllWindows()

# mac에서 opencv 팝업창 안닫힐때 뒤에 항상 붙여주기
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)

-1

### 직선
직선의 종류
1. cv2.LINE_4 : 상하좌우 4방향으로 연결된 선
2. cv2.LINE_8 : 대각선을 포함한 8방향으로 연결된 선 (기본값)
3. cv2.LINE_AA : 부드러운 선 (anti-aliasing)

In [8]:
import cv2
import numpy as np 

sketchbook = np.zeros((480, 640, 3), dtype = np.uint8)

COLOR = (0, 255, 255) # BGR : 노란색
THICKNESS = 3 # 두께

cv2.line (sketchbook, (50, 100), (400, 50), COLOR, THICKNESS, cv2.LINE_8)
cv2.line (sketchbook, (50, 200), (400, 50), COLOR, THICKNESS, cv2.LINE_4)
cv2.line (sketchbook, (50, 300), (400, 50), COLOR, THICKNESS, cv2.LINE_AA)
# 어디에, 시작점, 끝점, 색깔, 두께, 선 종류

cv2.imshow ('img', sketchbook)
cv2.waitKey(0)
cv2.destroyAllWindows()

# mac에서 opencv 팝업창 안닫힐때 뒤에 항상 붙여주기
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)

-1

### 원

In [18]:
import cv2
import numpy as np 

sketchbook = np.zeros((480, 640, 3), dtype = np.uint8)

COLOR = (255, 0, 0) # BGR : 파란색
RADIUS = 50 # 반지름
THICKNESS = 10 # 두께

cv2.circle(sketchbook, (200, 100), RADIUS, COLOR, THICKNESS, cv2.LINE_AA)
# 어디에, 원 중심점, 반지름, 색, 두께, 선 종류
cv2.circle(sketchbook, (400, 100), RADIUS, COLOR, cv2.FILLED, cv2.LINE_AA)
# thickness 부분을 filled or -1 = 속이 꽉 찬 원

cv2.imshow ('img', sketchbook)
cv2.waitKey(0)
cv2.destroyAllWindows()

# mac에서 opencv 팝업창 안닫힐때 뒤에 항상 붙여주기
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)

-1

### 사각형

In [27]:
import cv2
import numpy as np 

sketchbook = np.zeros((480, 640, 3), dtype = np.uint8)

COLOR = (90, 90, 180) # BGR : 핑크색
THICKNESS = 5 # 두께

cv2.rectangle (sketchbook, (100, 100), (200, 200), COLOR, THICKNESS, cv2.LINE_AA)
# 어디에, 왼쪽 위 꼭짓점, 오른쪽 아래 꼭짓점, 색, 두께, 선 종류 
cv2.rectangle (sketchbook, (300, 100), (400, 200), COLOR, cv2.FILLED, cv2.LINE_AA)
# thickness 부분을 filled or -1 = 속이 꽉 찬 사각형

cv2.imshow ('img', sketchbook)
cv2.waitKey(0)
cv2.destroyAllWindows()

# mac에서 opencv 팝업창 안닫힐때 뒤에 항상 붙여주기
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)

-1

### 다각형

In [9]:
import cv2
import numpy as np 

sketchbook = np.zeros((480, 640, 3), dtype = np.uint8)

COLOR = (255, 10, 150) # BGR : 보라색
THICKNESS = 5 # 두께

# 다각형은 각각의 꼭짓점 좌표를 정해줘야 함
pts1 = np.array ([[100, 100], [200, 100], [100, 200]]) # 삼각형
cv2.polylines(sketchbook, [pts1], True, COLOR, THICKNESS, cv2.LINE_AA)
# 어디에, [좌표], 열림여부, 색, 두께, 선
# 열림여부 - True : 닫힘, False : 열림

pts2 = np.array ([[200, 100], [300, 100], [300, 200]])
cv2.polylines(sketchbook, [pts2], True, COLOR, THICKNESS, cv2.LINE_AA)

pts3 = np.array ([[400, 400], [400, 500], [500, 500], [500, 400]])
pts4 = np.array ([[300, 300], [300, 340], [340, 340], [340, 300]])
cv2.polylines (sketchbook, [pts3, pts4], True, COLOR, THICKNESS, cv2.LINE_AA)
# 한꺼번에 그릴 수도 있음

cv2.imshow ('img', sketchbook)
cv2.waitKey(0)
cv2.destroyAllWindows()

# mac에서 opencv 팝업창 안닫힐때 뒤에 항상 붙여주기
cv2.destroyAllWindows()
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)
cv2.waitKey(1)

-1